name: Braid DB CI
on:
  - pull_request
  - push

jobs:
  ci:
    name: Run Braid DB CI Testing
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Set target python version
        uses: actions/setup-python@v2
        with:
          python-version: "3.8.x"

      - name: Install mpich
        run: sudo apt-get install -y mpich

      - name: Install poetry
        run: python -m pip install poetry

      - name: Install the project and dependencies
        run: poetry install

      - name: Run core tests
        run: test/test-core.sh

      - name: Run workflow tests
        run: test/test-workflows.sh

      - name: Run pytest tests
        run: poetry run pytest pytests/
